cluster:
  name: "matyix-cicd-cluster"
  provider: "google"

workspace:
  base: /go
  path: src/github.com/matyix/hooktest
  
pipeline:
  print_env:
    image: golang:1.10
    commands:
    - pwd
    - env
    - find .
    - sleep 2
    group: build

  test:
    image: golang:1.10
    commands:
    - mkdir $HOME/config
    - cp config/config.toml.example $HOME/config/config.toml
    - make test
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: 227d4cce-6bf7-30bb-2e2a-acc854318cof

  build_container:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: banzaicloud/pipeline
    tags: {{ printf "cicd-%s" (.DRONE_COMMIT_SHA | trunc 7) }}
    log: debug



    

